/*
 *  MIT License
 *
 *  Copyright (c) 2019-2020 Basile Combet, Philippe Yi
 *
 *  Permission is hereby granted, free of charge, to any person obtaining a copy
 *  of this software and associated documentation files (the "Software"), to deal
 *  in the Software without restriction, including without limitation the rights
 *  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 *  copies of the Software, and to permit persons to whom the Software is
 *  furnished to do so, subject to the following conditions:
 *
 *  The above copyright notice and this permission notice shall be included in all
 *  copies or substantial portions of the Software.
 *
 *  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 *  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 *  FITNESS FOR A PARTICULAR PURPOSE AND NON INFRINGEMENT. IN NO EVENT SHALL THE
 *  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 *  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 *  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 *  SOFTWARE.
 */

#pragma once

#include "Meta/Meta.hpp"

// FOREACH macro definitions, 70 args max are supported
#define RUKEN_FOR_EACH(action,...) RUKEN_SELECT_VARIADIC(__VA_ARGS__, RUKEN_FOR_EACH_INTERNAL_DO_70, RUKEN_FOR_EACH_INTERNAL_DO_69, RUKEN_FOR_EACH_INTERNAL_DO_68, RUKEN_FOR_EACH_INTERNAL_DO_67, RUKEN_FOR_EACH_INTERNAL_DO_66, RUKEN_FOR_EACH_INTERNAL_DO_65, RUKEN_FOR_EACH_INTERNAL_DO_64, RUKEN_FOR_EACH_INTERNAL_DO_63, RUKEN_FOR_EACH_INTERNAL_DO_62, RUKEN_FOR_EACH_INTERNAL_DO_61, RUKEN_FOR_EACH_INTERNAL_DO_60, RUKEN_FOR_EACH_INTERNAL_DO_59, RUKEN_FOR_EACH_INTERNAL_DO_58, RUKEN_FOR_EACH_INTERNAL_DO_57, RUKEN_FOR_EACH_INTERNAL_DO_56, RUKEN_FOR_EACH_INTERNAL_DO_55, RUKEN_FOR_EACH_INTERNAL_DO_54, RUKEN_FOR_EACH_INTERNAL_DO_53, RUKEN_FOR_EACH_INTERNAL_DO_52, RUKEN_FOR_EACH_INTERNAL_DO_51, RUKEN_FOR_EACH_INTERNAL_DO_50, RUKEN_FOR_EACH_INTERNAL_DO_49, RUKEN_FOR_EACH_INTERNAL_DO_48, RUKEN_FOR_EACH_INTERNAL_DO_47, RUKEN_FOR_EACH_INTERNAL_DO_46, RUKEN_FOR_EACH_INTERNAL_DO_45, RUKEN_FOR_EACH_INTERNAL_DO_44, RUKEN_FOR_EACH_INTERNAL_DO_43, RUKEN_FOR_EACH_INTERNAL_DO_42, RUKEN_FOR_EACH_INTERNAL_DO_41, RUKEN_FOR_EACH_INTERNAL_DO_40, RUKEN_FOR_EACH_INTERNAL_DO_39, RUKEN_FOR_EACH_INTERNAL_DO_38, RUKEN_FOR_EACH_INTERNAL_DO_37, RUKEN_FOR_EACH_INTERNAL_DO_36, RUKEN_FOR_EACH_INTERNAL_DO_35, RUKEN_FOR_EACH_INTERNAL_DO_34, RUKEN_FOR_EACH_INTERNAL_DO_33, RUKEN_FOR_EACH_INTERNAL_DO_32, RUKEN_FOR_EACH_INTERNAL_DO_31, RUKEN_FOR_EACH_INTERNAL_DO_30, RUKEN_FOR_EACH_INTERNAL_DO_29, RUKEN_FOR_EACH_INTERNAL_DO_28, RUKEN_FOR_EACH_INTERNAL_DO_27, RUKEN_FOR_EACH_INTERNAL_DO_26, RUKEN_FOR_EACH_INTERNAL_DO_25, RUKEN_FOR_EACH_INTERNAL_DO_24, RUKEN_FOR_EACH_INTERNAL_DO_23, RUKEN_FOR_EACH_INTERNAL_DO_22, RUKEN_FOR_EACH_INTERNAL_DO_21, RUKEN_FOR_EACH_INTERNAL_DO_20, RUKEN_FOR_EACH_INTERNAL_DO_19, RUKEN_FOR_EACH_INTERNAL_DO_18, RUKEN_FOR_EACH_INTERNAL_DO_17, RUKEN_FOR_EACH_INTERNAL_DO_16, RUKEN_FOR_EACH_INTERNAL_DO_15, RUKEN_FOR_EACH_INTERNAL_DO_14, RUKEN_FOR_EACH_INTERNAL_DO_13, RUKEN_FOR_EACH_INTERNAL_DO_12, RUKEN_FOR_EACH_INTERNAL_DO_11, RUKEN_FOR_EACH_INTERNAL_DO_10, RUKEN_FOR_EACH_INTERNAL_DO_9, RUKEN_FOR_EACH_INTERNAL_DO_8, RUKEN_FOR_EACH_INTERNAL_DO_7, RUKEN_FOR_EACH_INTERNAL_DO_6, RUKEN_FOR_EACH_INTERNAL_DO_5, RUKEN_FOR_EACH_INTERNAL_DO_4, RUKEN_FOR_EACH_INTERNAL_DO_3, RUKEN_FOR_EACH_INTERNAL_DO_2, RUKEN_FOR_EACH_INTERNAL_DO_1)(action,__VA_ARGS__)

// Single argument support
#define RUKEN_FOR_EACH_INTERNAL_DO_1(WHAT, X) WHAT(X)
#define RUKEN_FOR_EACH_INTERNAL_DO_2(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_1(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_3(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_2(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_4(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_3(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_5(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_4(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_6(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_5(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_7(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_6(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_8(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_7(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_9(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_8(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_10(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_9(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_11(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_10(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_12(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_11(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_13(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_12(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_14(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_13(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_15(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_14(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_16(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_15(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_17(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_16(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_18(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_17(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_19(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_18(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_20(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_19(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_21(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_20(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_22(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_21(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_23(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_22(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_24(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_23(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_25(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_24(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_26(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_25(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_27(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_26(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_28(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_27(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_29(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_28(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_30(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_29(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_31(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_30(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_32(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_31(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_33(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_32(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_34(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_33(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_35(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_34(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_36(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_35(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_37(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_36(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_38(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_37(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_39(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_38(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_40(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_39(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_41(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_40(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_42(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_41(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_43(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_42(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_44(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_43(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_45(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_44(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_46(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_45(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_47(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_46(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_48(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_47(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_49(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_48(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_50(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_49(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_51(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_50(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_52(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_51(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_53(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_52(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_54(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_53(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_55(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_54(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_56(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_55(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_57(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_56(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_58(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_57(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_59(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_58(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_60(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_59(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_61(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_60(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_62(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_61(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_63(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_62(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_64(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_63(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_65(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_64(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_66(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_65(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_67(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_66(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_68(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_67(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_69(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_68(WHAT, __VA_ARGS__)
#define RUKEN_FOR_EACH_INTERNAL_DO_70(WHAT, X, ...) WHAT(X)RUKEN_FOR_EACH_INTERNAL_DO_69(WHAT, __VA_ARGS__)